version: '3.7'
services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - '4563-4584:4563-4584'
    environment:
      - SERVICES=dynamodb
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - ./tmp/localstack:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock

